Use the windows crate to search for the Windows installation time.
google/rrg pull request #56
Opened 2022-11-07 21:29 UTC by diceride

Uses the [windows](https://crates.io/crates/windows) crate to search for the installation date in the registry. The aim is to limit the used Windows API crates. 

References
- Windows: [RegGetValueW function](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetvaluew)

2022-11-09 10:01 UTC, panhania requested changes

2022-11-09 10:01 UTC, panhania commented on src/action/insttime.rs
> +            return Some(SystemTime::UNIX_EPOCH + Duration::from_secs(install_date as u64))
Prefer not to use `as` casts as they don't shield from potential overflow issues. `u64::from` does not have these issues.

2022-11-10 15:18 UTC, diceride commented
- Replaced the windows crate with the lightweight windows-sys crate.
- Used `u64::from` to convert from u32 losslessly.

2022-11-15 05:29 UTC, panhania approved these changes

2022-11-15 05:30 UTC, panhania commented
@diceride Looks good now but has merge conflicts. Could you look into resolving them?

2022-11-15 21:55 UTC, diceride commented
Bim bam bum late night merge errors and broken Windows vm's are much fun 🐼

2022-11-16 10:52 UTC, merged