Add command line argument for signature verification key
google/rrg pull request #80
Opened 2024-12-18 13:13 UTC by s-westphal

2025-01-13 10:45 UTC, panhania requested changes

2025-01-13 10:45 UTC, panhania commented on crates/rrg/Cargo.toml
> +]
If I understand correctly, we only need `rand_core` for testing, so it should be only specified in `dev-dependencies`.

2025-01-13 10:45 UTC, panhania commented on crates/rrg/src/args.rs
> +       description="verification key for signed commands",
Let's specify that it expects hex encoded bytes, e.g. _"verification key for signed commands (hex-encoded bytes)"_.

2025-01-13 10:45 UTC, panhania commented on crates/rrg/Cargo.toml
> +version = "0.4.3"
Let's not bring a third-party dependency for something that can be trivially implemented in a few lines ourselves.

2025-01-13 15:05 UTC, s-westphal commented on crates/rrg/Cargo.toml
> +]
Yes exactly! Updated.

2025-01-13 15:05 UTC, s-westphal commented on crates/rrg/src/args.rs
> +       description="verification key for signed commands",
Done!

2025-01-13 15:06 UTC, s-westphal commented on crates/rrg/Cargo.toml
> +version = "0.4.3"
Alright, I added the function with some tests.

2025-01-14 11:32 UTC, panhania requested changes

2025-01-14 11:32 UTC, panhania commented on crates/rrg/src/args.rs
> +fn hex_decode(hex: Vec<u8>) -> Result<Vec<u8>, HexDecodeError> {
I understand that you named it after `hex::decode` but the convention for functions is that they usually start with a verb, so a more appropriate name would be `decode_hex` (and changing the function name should also affect name of the error struct).

2025-01-14 11:32 UTC, panhania commented on crates/rrg/src/args.rs
> +fn hex_decode(hex: Vec<u8>) -> Result<Vec<u8>, HexDecodeError> {
Accepting an owned vector that is consumed by the function is indication that you should probably accept a slice (`&[u8]`).

The original [`hex::decode`](https://docs.rs/hex/latest/hex/fn.decode.html) goes even a step further an accepts `AsRef<[u8]>`, so will work both with `Vec`s and slices without any additional borrows, although I don't think we need that level of generality here.

2025-01-14 11:32 UTC, panhania commented on crates/rrg/src/args.rs
> +struct HexDecodeError();
No need for `()`, you can just have `struct Foo;` (you will also need to change creation not to use parens).

2025-01-14 11:32 UTC, panhania commented on crates/rrg/src/args.rs
> +    }
No need to use `test_*` prefix in test names, `#[test]` annotation is enough and adding it just introduces noise. You can still occasionally see old tests with `test_*` prefix in the codebase but consider this legacy back from days when I was still young.

At the same time, tests *should* be prefixed with the name of the function or type they test. At the moment in this module we only test `hex_decode`, but the moment we want to test other stuff, things can start to get confusing.

To sum up, I would rename these (after including the function name change) like `decode_hex_invalid_length`, etc.

2025-01-14 11:32 UTC, panhania commented on crates/rrg/src/args.rs
> +    pub fn test_empty() {
`pub` is unnecessary here.

2025-01-14 11:32 UTC, panhania commented on crates/rrg/src/args.rs
> +        let hex = vec![b'a', b'2', b'8', b'F'];
If you apply the suggestion for the function to take slices instead of `Vec`s, you can use bytestring literals, e.g. `b"a28F"`.

2025-01-14 11:32 UTC, panhania commented on crates/rrg/src/args.rs
> +        let hex = vec![b'a', b'2', b'8', b'F'];
I would split this into two cases: one with lowercase letters and one with uppercase letters.

2025-01-14 18:50 UTC, s-westphal commented on crates/rrg/src/args.rs
> +fn hex_decode(hex: Vec<u8>) -> Result<Vec<u8>, HexDecodeError> {
Done.

2025-01-14 18:50 UTC, s-westphal commented on crates/rrg/src/args.rs
> +fn hex_decode(hex: Vec<u8>) -> Result<Vec<u8>, HexDecodeError> {
Done.

2025-01-14 18:50 UTC, s-westphal commented on crates/rrg/src/args.rs
> +    }
Done.

2025-01-14 18:50 UTC, s-westphal commented on crates/rrg/src/args.rs
> +        let hex = vec![b'a', b'2', b'8', b'F'];
Done.

2025-01-14 18:50 UTC, s-westphal commented on crates/rrg/src/args.rs
> +        let hex = vec![b'a', b'2', b'8', b'F'];
Done.

2025-01-14 18:51 UTC, s-westphal commented on crates/rrg/src/args.rs
> +    pub fn test_empty() {
Done.

2025-01-14 18:51 UTC, s-westphal commented on crates/rrg/src/args.rs
> +struct HexDecodeError();
Done.

2025-01-15 11:06 UTC, panhania approved these changes

2025-01-15 11:11 UTC, merged